### ISSUE TITLE
File: README.md

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/pair-session-chat#8]
Included in our README is:

 - Project Name
 - Project Short Description
 - Project Production URL
 - Imgs of both Main components of the App
 - Contributors Information
 - Sprint equivalent: Sessions description including duration and objectives and snap of what was done individually after each of them

> I believe the Order in which those elements are displayed should be better organized 
> More importantly, attempt to generate a GIF was a failure lol =(
> We should mention the MIT license at the end of that documentation

**Comment by johnmal-dev** [comment]
Please review and revise my latest pull request.
Still to-do:
- We should mention the MIT license at the end of that documentation

**Comment by Medic1111** [comment]
Absolutely nailed it!
ps: Feel free to MERGE at your will to the dev branch as you are admin =)

**Comment by Medic1111** [comment]
Complete: Thanks to John! =)
